#!/usr/bin/env bash
# =============================================================================
# SEC-06: Split portal.env into config + secrets
# =============================================================================
# Splits an existing portal.env into:
#   portal.env          - Non-sensitive configuration (hosts, ports, flags, etc.)
#   portal.secrets.env  - Sensitive credentials (passwords, keys, secrets)
#
# Usage: ./split_portal_env.sh [--dry-run] [--portal-env PATH]
# =============================================================================

set -euo pipefail

# Patterns that identify sensitive keys (matched against the KEY part before '=')
SENSITIVE_PATTERNS=(
    "PASSWORD"
    "SECRET"
    "_API_KEY="
    "ENCRYPTION_KEY"
    "ConnectionStrings__"
    "_TOKEN="
)

# Defaults
DRY_RUN=false
PORTAL_ENV=""

# Parse arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        --portal-env)
            PORTAL_ENV="$2"
            shift 2
            ;;
        -h|--help)
            echo "Usage: $0 [--dry-run] [--portal-env PATH]"
            echo ""
            echo "Splits portal.env into portal.env (config) + portal.secrets.env (credentials)"
            echo ""
            echo "Options:"
            echo "  --dry-run       Show what would be split without making changes"
            echo "  --portal-env    Path to portal.env (default: auto-detect)"
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

# Find portal.env
if [[ -z "$PORTAL_ENV" ]]; then
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    if [[ -f "${SCRIPT_DIR}/portal.env" ]]; then
        PORTAL_ENV="${SCRIPT_DIR}/portal.env"
    elif [[ -f "./portal.env" ]]; then
        PORTAL_ENV="./portal.env"
    else
        echo "ERROR: portal.env not found. Use --portal-env to specify the path."
        exit 1
    fi
fi

DEPLOY_DIR="$(dirname "$PORTAL_ENV")"
SECRETS_FILE="${DEPLOY_DIR}/portal.secrets.env"

if [[ ! -f "$PORTAL_ENV" ]]; then
    echo "ERROR: File not found: $PORTAL_ENV"
    exit 1
fi

if [[ -f "$SECRETS_FILE" ]] && [[ "$DRY_RUN" == "false" ]]; then
    echo "WARNING: $SECRETS_FILE already exists."
    echo "This script is for one-time migration from a combined portal.env."
    read -rp "Overwrite? [y/N] " confirm
    if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
        echo "Aborted."
        exit 0
    fi
fi

# Check if key matches sensitive patterns
is_sensitive_key() {
    local key="$1"
    for pattern in "${SENSITIVE_PATTERNS[@]}"; do
        if [[ "$key" == *"$pattern"* ]]; then
            return 0
        fi
    done
    return 1
}

# Process the file
config_lines=()
secrets_lines=()
config_count=0
secrets_count=0

# Add header to secrets
secrets_lines+=("# =============================================================================")
secrets_lines+=("# EZY Portal - Secrets (GENERATED by split_portal_env.sh)")
secrets_lines+=("# =============================================================================")
secrets_lines+=("# This file contains sensitive credentials. Keep it secure (chmod 600).")
secrets_lines+=("# DO NOT commit this file to version control.")
secrets_lines+=("# =============================================================================")
secrets_lines+=("")

while IFS= read -r line || [[ -n "$line" ]]; do
    # Empty lines and comments go to config
    if [[ -z "$line" ]] || [[ "$line" =~ ^[[:space:]]*# ]]; then
        config_lines+=("$line")
        continue
    fi

    # Extract key (everything before first '=')
    if [[ "$line" =~ ^([A-Za-z_][A-Za-z0-9_.]*)= ]]; then
        local_key="${BASH_REMATCH[1]}"

        if is_sensitive_key "$local_key"; then
            secrets_lines+=("$line")
            ((secrets_count++))
            # Add a comment in config file pointing to secrets
            config_lines+=("# ${local_key} is in portal.secrets.env")
        else
            config_lines+=("$line")
            ((config_count++))
        fi
    else
        # Non-standard lines (shouldn't happen) go to config
        config_lines+=("$line")
    fi
done < "$PORTAL_ENV"

echo "=== Split Summary ==="
echo "Source:          $PORTAL_ENV"
echo "Config values:   $config_count → portal.env"
echo "Secret values:   $secrets_count → portal.secrets.env"
echo ""

if [[ "$DRY_RUN" == "true" ]]; then
    echo "--- Secrets that would be moved ---"
    for line in "${secrets_lines[@]}"; do
        if [[ "$line" =~ ^[A-Za-z_] ]]; then
            key="${line%%=*}"
            echo "  $key"
        fi
    done
    echo ""
    echo "(Dry run - no files modified)"
    exit 0
fi

# Backup original
cp "$PORTAL_ENV" "${PORTAL_ENV}.pre-split.bak"
echo "Backup created: ${PORTAL_ENV}.pre-split.bak"

# Write config file
printf '%s\n' "${config_lines[@]}" > "$PORTAL_ENV"

# Write secrets file
printf '%s\n' "${secrets_lines[@]}" > "$SECRETS_FILE"
chmod 600 "$SECRETS_FILE"

echo ""
echo "Done!"
echo "  Config:  $PORTAL_ENV ($config_count values)"
echo "  Secrets: $SECRETS_FILE ($secrets_count values, chmod 600)"
echo ""
echo "IMPORTANT: Delete old backups that contain the unsplit portal.env with secrets."
echo "Check: backups/ directory for any previous portal.env copies."
